name: iris-mlops-env
channels:
- defaults
- conda-forge
dependencies:
- blas
- bottleneck
- bzip2
- ca-certificates
- expat
- joblib
- libcxx
- libffi
- libgfortran
- libgfortran5
- libopenblas
- llvm-openmp
- ncurses
- numexpr
- openssl
- pandas
- pip
- pybind11-abi
- python
- python-dateutil
- python-tzdata
- readline
- scikit-learn
- scipy
- setuptools
- six
- sqlite
- threadpoolctl
- tk
- tzdata
- wheel
- xz
- zlib
- pip:
  - aiobotocore==2.24.0
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.12.15
  - aiohttp-retry==2.9.1
  - aioitertools==0.12.0
  - aiosignal==1.4.0
  - alembic==1.16.4
  - amqp==5.3.1
  - annotated-types==0.7.0
  - antlr4-python3-runtime==4.9.3
  - anyio==4.10.0
  - appdirs==1.4.4
  - async-timeout==5.0.1
  - asyncssh==2.21.0
  - atpublic==6.0.1
  - attrs==25.3.0
  - billiard==4.2.1
  - blinker==1.9.0
  - boto3==1.39.11
  - botocore==1.39.11
  - cachetools==5.5.2
  - celery==5.5.3
  - certifi==2025.8.3
  - cffi==1.17.1
  - charset-normalizer==3.4.3
  - click==8.1.8
  - click-didyoumean==0.3.1
  - click-plugins==1.1.1.2
  - click-repl==0.3.0
  - cloudpickle==3.1.1
  - colorama==0.4.6
  - configobj==5.0.9
  - contourpy==1.3.0
  - cryptography==43.0.3
  - cycler==0.12.1
  - databricks-cli==0.18.0
  - databricks-sdk==0.62.0
  - dictdiffer==0.9.0
  - diskcache==5.6.3
  - distro==1.9.0
  - docker==6.1.3
  - dpath==2.2.0
  - dulwich==0.24.1
  - dvc==3.61.0
  - dvc-data==3.16.11
  - dvc-gdrive==3.0.1
  - dvc-http==2.32.0
  - dvc-objects==5.1.1
  - dvc-render==1.0.2
  - dvc-s3==3.2.2
  - dvc-studio-client==0.22.0
  - dvc-task==0.40.2
  - entrypoints==0.4
  - exceptiongroup==1.3.0
  - fastapi==0.116.1
  - filelock==3.18.0
  - flask==3.1.1
  - flatten-dict==0.4.2
  - flufl-lock==8.2.0
  - fonttools==4.59.0
  - frozenlist==1.7.0
  - fsspec==2025.7.0
  - funcy==2.0
  - gitdb==4.0.12
  - gitpython==3.1.45
  - google-api-core==2.25.1
  - google-api-python-client==2.178.0
  - google-auth==2.40.3
  - google-auth-httplib2==0.2.0
  - googleapis-common-protos==1.70.0
  - grandalf==0.8
  - graphene==3.4.3
  - graphql-core==3.2.6
  - graphql-relay==3.2.0
  - gto==1.7.2
  - gunicorn==21.2.0
  - h11==0.16.0
  - httplib2==0.22.0
  - hydra-core==1.3.2
  - idna==3.10
  - importlib-metadata==7.2.1
  - importlib-resources==6.5.2
  - iterative-telemetry==0.0.10
  - itsdangerous==2.2.0
  - jinja2==3.1.6
  - jmespath==1.0.1
  - kiwisolver==1.4.7
  - kombu==5.5.4
  - mako==1.3.10
  - markdown==3.8.2
  - markdown-it-py==3.0.0
  - markupsafe==3.0.2
  - matplotlib==3.9.4
  - mdurl==0.1.2
  - mlflow==2.9.2
  - multidict==6.6.3
  - networkx==3.2.1
  - numpy==1.26.4
  - oauth2client==4.1.3
  - oauthlib==3.3.1
  - omegaconf==2.3.0
  - opentelemetry-api==1.36.0
  - opentelemetry-sdk==1.36.0
  - opentelemetry-semantic-conventions==0.57b0
  - orjson==3.11.1
  - packaging==23.2
  - pathspec==0.12.1
  - pillow==11.3.0
  - platformdirs==4.3.8
  - prompt-toolkit==3.0.51
  - propcache==0.3.2
  - proto-plus==1.26.1
  - protobuf==4.25.8
  - psutil==7.0.0
  - pyarrow==14.0.2
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.2
  - pycparser==2.22
  - pydantic==2.11.7
  - pydantic-core==2.33.2
  - pydot==4.0.1
  - pydrive2==1.21.3
  - pygit2==1.15.1
  - pygments==2.19.2
  - pygtrie==2.5.0
  - pyjwt==2.10.1
  - pyopenssl==24.2.1
  - pyparsing==3.2.3
  - python-dotenv==1.1.1
  - pytz==2023.4
  - pyyaml==6.0.2
  - querystring-parser==1.2.4
  - requests==2.32.4
  - rich==14.1.0
  - rsa==4.9.1
  - ruamel-yaml==0.18.14
  - ruamel-yaml-clib==0.2.12
  - s3fs==2025.7.0
  - s3transfer==0.13.1
  - scmrepo==3.5.2
  - semver==3.0.4
  - shellingham==1.5.4
  - shortuuid==1.0.13
  - shtab==1.7.2
  - smmap==5.0.2
  - sniffio==1.3.1
  - sqlalchemy==2.0.42
  - sqlparse==0.5.3
  - sqltrie==0.11.2
  - starlette==0.47.2
  - tabulate==0.9.0
  - tomli==2.2.1
  - tomlkit==0.13.3
  - tqdm==4.67.1
  - typer==0.16.0
  - typing-extensions==4.14.1
  - typing-inspection==0.4.1
  - uritemplate==4.2.0
  - urllib3==1.26.20
  - uvicorn==0.35.0
  - vine==5.1.0
  - voluptuous==0.15.2
  - wcwidth==0.2.13
  - websocket-client==1.8.0
  - werkzeug==3.1.3
  - wrapt==1.17.2
  - yarl==1.20.1
  - zc-lockfile==3.0.post1
  - zipp==3.23.0
