name: Docker Publish

on:
  workflow_run:
    workflows: ['Lint and Test']
    types:
      - completed

jobs:
  version-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Needed to detect merge commits

      - name: Detect merge commit
        id: merge_check
        run: |
          MERGE_COMMIT=$(git log -1 --pretty=%P | wc -w)
          if [ "$MERGE_COMMIT" -lt 2 ]; then
            echo "Not a merge commit. Skipping."
            exit 0
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pydantic uvicorn dotenv mlflow commitizen

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Bump minor version
        id: bump
        run: |
          cz bump --increment minor --yes
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git push origin HEAD --tags || echo "Nothing to push"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            vinodmlops/iris:latest
            vinodmlops/iris:${{ env.VERSION }}
